# Generated by Django 4.0 on 2021-12-24 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_list', models.TextField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_prescriptions', to='user.user')),
                ('prescriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescribed_prescriptions', to='user.user')),
            ],
        ),
    ]
