# Generated by Django 4.0 on 2021-12-24 13:52

from django.db import migrations, models
import django.utils.timezone
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('national_code', models.CharField(max_length=10, unique=True, validators=[user.models.validate_digit_length])),
                ('password', models.CharField(max_length=128)),
                ('isAdmin', models.BooleanField(default=False)),
                ('isDoctor', models.BooleanField(default=False)),
                ('token', models.CharField(default='', max_length=256)),
                ('token_exp_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('bio', models.CharField(default='bio', max_length=128)),
                ('sign_up_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
